"""product_udpate_schema

Revision ID: a274e76f04d9
Revises: eae03b03b618
Create Date: 2026-07-01 18:52:36.268818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'a274e76f04d9'
down_revision: Union[str, Sequence[str], None] = 'eae03b03b618'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('selling_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('products', sa.Column('description', sa.String(), nullable=True))
    op.add_column('products', sa.Column('target_audience', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('pain_points', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('products', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.alter_column('products', 'buying_price',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.drop_column('products', 'raw_description')
    op.drop_column('products', 'raw_problems')
    op.drop_column('products', 'raw_audience')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('raw_audience', sqlite.JSON(), nullable=True))
    op.add_column('products', sa.Column('raw_problems', sqlite.JSON(), nullable=True))
    op.add_column('products', sa.Column('raw_description', sa.VARCHAR(), nullable=True))
    op.alter_column('products', 'buying_price',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'created_at')
    op.drop_column('products', 'pain_points')
    op.drop_column('products', 'target_audience')
    op.drop_column('products', 'description')
    op.drop_column('products', 'selling_price')
    # ### end Alembic commands ###
